name: Docker Build and Publish

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  # 确保使用完整的镜像名称，包含组织/用户名
  DOCKER_HUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/docker-rgo
  GHCR_REPO: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 登录到 GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_HUB_REPO }}:latest
            ${{ env.GHCR_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
